// <auto-generated />
using System;
using GorevTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace gt.Migrations
{
    [DbContext(typeof(GorevDbContext))]
    partial class GorevDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GorevTakip.Models.Gorev", b =>
                {
                    b.Property<long>("GorevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GorevId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("KategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<int>("Oncelik")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GorevId");

                    b.HasIndex("BitisTarihi");

                    b.HasIndex("Durum");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.Property<long>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KategoriId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KategoriId");

                    b.HasIndex("KullaniciId", "KategoriAd")
                        .IsUnique();

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriId = 1L,
                            Aciklama = "İşle ilgili görevler ve toplantılar",
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriAd = "İş",
                            KullaniciId = 1L,
                            Renk = "primary"
                        },
                        new
                        {
                            KategoriId = 2L,
                            Aciklama = "Ders, ödev ve sınav hazırlıkları",
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriAd = "Okul",
                            KullaniciId = 1L,
                            Renk = "success"
                        },
                        new
                        {
                            KategoriId = 3L,
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriAd = "Ev",
                            KullaniciId = 1L,
                            Renk = "warning"
                        },
                        new
                        {
                            KategoriId = 4L,
                            Aciklama = "Kişisel gelişim ve sağlık",
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriAd = "Kişisel",
                            KullaniciId = 1L,
                            Renk = "info"
                        });
                });

            modelBuilder.Entity("GorevTakip.Models.Kullanici", b =>
                {
                    b.Property<long>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciId = 1L,
                            AdSoyad = "Sistem Yöneticisi",
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            SifreHash = "EC7F93F0A99692C1F91E696226BF3F4C0F711A0380921642B466A62C1628C440"
                        });
                });

            modelBuilder.Entity("GorevTakip.Models.Gorev", b =>
                {
                    b.HasOne("GorevTakip.Models.Kategori", "Kategori")
                        .WithMany("Gorevler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GorevTakip.Models.Kullanici", "Kullanici")
                        .WithMany("Gorevler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.HasOne("GorevTakip.Models.Kullanici", "Kullanici")
                        .WithMany("Kategoriler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kullanici", b =>
                {
                    b.Navigation("Gorevler");

                    b.Navigation("Kategoriler");
                });
#pragma warning restore 612, 618
        }
    }
}
